### ISSUE TITLE
Confused with using named constructor

### ISSUE THREAD

**Issue by thrashzone13** [Ocramius/doctrine-best-practices#4]
Hey
Thanks for these amazing slides, but I'm a little bit confused.
52th slide says that named constructors are okay but then on 55th it's mentioned as a bad idea.

**Comment by Ocramius** [comment]
https://ocramius.github.io/doctrine-best-practices/#/55 is not about named ctor issues, but rather domain depending on infrastructural component (dependency from `User` to `Form`)

**Comment by thrashzone13** [comment]
Oh that's right. I'm still not sure about the best way to do crud in my controllers with doctrine entities and I couldn't find any clear example.
